services:
  - type: web
    name: resume-scanner-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python download_model.py
    startCommand: gunicorn api:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: OPENCORPORATES_API_TOKEN
        sync: false
