services:
  - type: web
    name: resume-scanner-api
    env: python
    buildCommand: pip install -r requirements.txt && python download_model.py
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: GITHUB_TOKEN
        sync: false
      - key: OPENCORPORATES_API_TOKEN
        sync: false
